/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'inverse-on-surface': '#303032',
        'tertiary-fixed-dim': '#b5c5fc',
        'primary-container': '#ffb300',
        'tertiary-fixed': '#dbe1ff',
        'on-tertiary-container': '#3d4d7d',
        'on-tertiary-fixed-variant': '#354574',
        'error-container': '#93000a',
        'on-primary-container': '#6b4900',
        'error': '#ffb4ab',
        'on-secondary-container': '#342800',
        'secondary-container': '#af8d11',
        'primary': '#ffd79b',
        'on-secondary': '#3c2f00',
        'primary-fixed': '#ffdeac',
        'on-secondary-fixed-variant': '#574500',
        'tertiary': '#d4dcff',
        'inverse-primary': '#7e5700',
        'on-error': '#690005',
        'surface-container-lowest': '#0e0e10',
        'background': '#131315',
        'tertiary-container': '#b0c0f7',
        'on-tertiary': '#1d2e5c',
        'surface-container': '#201f21',
        'outline-variant': '#514532',
        'surface-dim': '#131315',
        'outline': '#9e8e78',
        'surface-container-highest': '#353437',
        'on-background': '#e5e1e4',
        'on-secondary-fixed': '#241a00',
        'surface': '#131315',
        'inverse-surface': '#e5e1e4',
        'on-tertiary-fixed': '#041846',
        'secondary': '#e9c349',
        'on-surface-variant': '#d6c4ac',
        'on-primary-fixed': '#281900',
        'secondary-fixed-dim': '#e9c349',
        'on-surface': '#e5e1e4',
        'surface-tint': '#ffba38',
        'on-error-container': '#ffdad6',
        'primary-fixed-dim': '#ffba38',
        'on-primary': '#432c00',
        'surface-bright': '#39393b',
        'secondary-fixed': '#ffe088',
        'surface-container-high': '#2a2a2c',
        'on-primary-fixed-variant': '#604100',
        'surface-variant': '#353437',
        'surface-container-low': '#1b1b1d',
        // Arctic Minimal theme
        'arctic-bg': '#f4f7fb',
        'arctic-surface': '#ffffff',
        'arctic-primary': '#2b4a8c',
        'arctic-accent': '#4a7fc1',
        'arctic-text': '#1a2a3a',
        // Rose Editorial theme
        'rose-bg': '#fdf0f3',
        'rose-surface': '#fff5f7',
        'rose-primary': '#8b1a3a',
        'rose-accent': '#c9436e',
        'rose-text': '#3a0f1a',
        // Terminal Green theme
        'terminal-bg': '#000000',
        'terminal-surface': '#0a0a0a',
        'terminal-primary': '#00ff41',
        'terminal-dim': '#00aa2b',
        'terminal-text': '#ccffcc',
      },
      fontFamily: {
        'display': ['"Playfair Display"', 'Georgia', 'serif'],
        'mono': ['"JetBrains Mono"', '"Fira Code"', 'monospace'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'code-snippet': ['13px', { lineHeight: '1.4', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '500' }],
      },
      spacing: {
        'xs': '4px',
        'sm': '8px',
        'md': '16px',
        'lg': '24px',
        'xl': '40px',
        'gutter': '16px',
        'margin-mobile': '16px',
        'margin-desktop': '32px',
        'max-width': '1280px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      keyframes: {
        fadeSlideUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideInRight: {
          '0%': { opacity: '0', transform: 'translateX(30px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        pulse: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.5' },
        },
        confettiBurst: {
          '0%': { transform: 'scale(0)', opacity: '1' },
          '100%': { transform: 'scale(3)', opacity: '0' },
        },
      },
      animation: {
        'fade-slide-up': 'fadeSlideUp 0.6s ease-out forwards',
        'fade-in': 'fadeIn 0.4s ease-out forwards',
        'slide-in-right': 'slideInRight 0.4s ease-out forwards',
        'pulse-slow': 'pulse 2s ease-in-out infinite',
      },
      boxShadow: {
        'terminal': '4px 4px 0px #000000',
        'terminal-lg': '8px 8px 0px #000000',
        'terminal-amber': '4px 4px 0px #ffb300',
      },
    },
  },
  plugins: [],
}
